# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sUcwdvF-STARxBg898MWA_c9TcFsLWsP
"""

import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense, Input, Dropout, Flatten
from keras import regularizers
from tensorflow.keras.callbacks import Callback
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical as to_catagorical
from tensorflow.keras.callbacks import TensorBoard
from os.path import join
import tensorflow as tf

(x_train,y_train),(x_test,y_test) =mnist.load_data()

y_train=to_catagorical(y_train,num_classes=10)
y_test=to_catagorical(y_test,num_classes=10)

model = Sequential()
model.add(Input(shape=(28, 28, 1)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(10, activation='softmax'))

log_dir=join('logs','fit','model1')
tfcb=tf.keras.callbacks.TensorBoard(log_dir=log_dir,histogram_freq=1,write_graph=True)

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

history = model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test), callbacks=[tfcb], batch_size=32)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir logs/fit

model1 = Sequential()
model1.add(Input(shape=(28, 28, 1)))
model1.add(Flatten())
model1.add(Dense(64, activation='relu'),regularizers.l2(0.01))
model1.add(Dense(32, activation='relu'),regularizers.l2(0.01))
model1.add(Dense(16, activation='relu'),regularizers.l2(0.01))
model1.add(Dense(10, activation='softmax'))

log_dir=join('logs','fit','model1')
tfcbs=tf.keras.callbacks.TensorBoard(log_dir=log_dir,histogram_freq=1,write_graph=True)

model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

history = model1.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test), callbacks=[tfcbs], batch_size=32)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir logs/fit

model2 = Sequential()
model2.add(Input(shape=(28, 28, 1)))
model2.add(Flatten())
model2.add(Dense(64, activation='relu'))
model2.add(Dropout(0.2))
model2.add(Dense(32, activation='relu'))
model2.add(Dense(16, activation='relu'))
model2.add(Dense(10, activation='softmax'))

log_dir = join('logs', 'fit', 'model2')
tfcbr = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1, write_graph=True)

model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

history = model1.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test), callbacks=[tfcbr], batch_size=32)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir logs/fit